---
title: "46-926 Homework 4, Part 2"
author: "Jingyi Guo, Pittsburgh Campus"
date: "2/13/2017"
output: pdf_document
---

```{r data,message=FALSE,results='hide'}
library(fANCOVA)
trainset = read.table("/Users/apple/Desktop/ML/train.csv", sep=",", header=T)
fullrow = rep(FALSE,nrow(trainset))
varnames = c(paste("Ret_",2:120, sep = ""))
```

## Use one-dimensional non-parametric regression to “smooth” the return series

```{r 1,warning=FALSE}
nonpara_fitted = matrix(nrow=22390,ncol=119)
for(i in 1:119)
{
  nonpara_fitted[,i]=loess(Ret_PlusOne ~ get(varnames[i]),data=trainset,subset=fullrow,span=0.4,degree=1)$fitted
}
nonpara_fitted=as.data.frame(nonpara_fitted)
```

## Fit the model using "smoothed" predictors:

linear regression:

```{r 1 new dataset}
y=trainset[208][fullrow,]
newvarnames=c(paste("V",1:119, sep = ""))
# Here V1, V2, ..., V119 refer to nonparametric fitted values of Ret_2, Ret_3, ..., 
# Ret_120 respectively, and y refer to Ret_PlusOne.
newform=as.formula(paste("y ~ ",paste(newvarnames,collapse = "+")))
lmfitmodel=lm(newform,data=nonpara_fitted)
summary(lmfitmodel)
AIC(lmfitmodel)
```



